[theme]

# Primary accent for interactive elements
primaryColor = '#79d191'

# Background color for the main content area
backgroundColor = '#d5eddc'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#0f302c'

# Color used for almost all text
textColor = '#394d3e'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "serif"
font = "monospace"
