[theme]

# Primary accent for interactive elements
primaryColor = '#1e3c42'

# Background color for the main content area
backgroundColor = '#a7bfc4'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#659199'

# Color used for almost all text
textColor = '#2c4347'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "serif"
font = "sans serif"
